
version: 2

models:
    - name: orders
      description: "Orders dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: order_items
      description: "Order items dbt model"
      columns:
          - name: order_item_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: order_details
      description: "Denormalized orders and order items dbt model"
      columns:
          - name: order_item_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
